#ifndef IDL_COLOR_TRACK_STRUCT
#define IDL_COLOR_TRACK_STRUCT

module or {
module ColorTrack {

  enum PlateState {
		   UNKNOWN, INTERESTING, TREATED, NOT_NTERESTING
  };

  struct PlateInfo {
    short index;
    PlateState state;
    or::t3d::pos coord;
  };

  struct PlateSequence{
    sequence<PlateInfo> seq;
  };

  // Color Information for blob detection
  struct ColorInfo {
    long r;
    long g;
    long b;
    long threshold;
  };

};
};

#endif
